logging:
    level:
        ROOT: ERROR
        com.clashhorn: DEBUG
        org.springframework: INFO
        
server:
    port: 8080
    static-content: file:../clash-horn-web-client/public/
    
clash-api:
    baseUrl: https://api.clashofclans.com/v1
    accessToken: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6ImRlZDUzYzczLTNmNTgtNGJmZC05NzAyLTIwZWRkNDBhOTNiNiIsImlhdCI6MTUwNTU2NjYxNiwic3ViIjoiZGV2ZWxvcGVyLzNhMTk2MmY1LWNjNmYtNzg1OC0wODViLTFmN2IxMTJlNjNiNSIsInNjb3BlcyI6WyJjbGFzaCJdLCJsaW1pdHMiOlt7InRpZXIiOiJkZXZlbG9wZXIvc2lsdmVyIiwidHlwZSI6InRocm90dGxpbmcifSx7ImNpZHJzIjpbIjU0LjE4Ny4yMjkuNjAiLCIxNzcuMTM0LjE3OC41MCJdLCJ0eXBlIjoiY2xpZW50In1dfQ.Gc5CzDtzFmSrfrkPVX4eV4I84SpZW089Q2erjDTV-kV3CoJrydkah-e6hrGO9ExyqWnk4arKftr0JcEgxZP65A
    
---
spring:
    profiles: guilaaf-dev
    
clash-api:
    accessToken: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6IjVkOWE0MTI3LWVlNDEtNGE4NS05NTZhLTA2ZDM4YjEyNDY4YiIsImlhdCI6MTUwNTM0MTEwNCwic3ViIjoiZGV2ZWxvcGVyLzA5YjFlMzcyLTA2M2MtYjA1OC03YjFjLWJmNzBjNDVjNTIyYSIsInNjb3BlcyI6WyJjbGFzaCJdLCJsaW1pdHMiOlt7InRpZXIiOiJkZXZlbG9wZXIvc2lsdmVyIiwidHlwZSI6InRocm90dGxpbmcifSx7ImNpZHJzIjpbIjE3Ny4xMzQuMTc4LjkxIl0sInR5cGUiOiJjbGllbnQifV19.0FZP5UzxsgkqYG2zFCN3yp8OviH7V3s3OMPpUYxnBl9ZD9cmOIhJFsgaK3hdWmrY_f7az31Q3x8xJ_D0C2NpAg

---
spring:
    profiles: production

logging:
    pattern:
        console: 
    file: /home/ec2-user/clash-horn.log

server:
    port: 80
    static-content: file:///home/ec2-user/clash-horn/clash-horn-web-client/public/
    
clash-api:
    accessToken: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6ImRlZDUzYzczLTNmNTgtNGJmZC05NzAyLTIwZWRkNDBhOTNiNiIsImlhdCI6MTUwNTU2NjYxNiwic3ViIjoiZGV2ZWxvcGVyLzNhMTk2MmY1LWNjNmYtNzg1OC0wODViLTFmN2IxMTJlNjNiNSIsInNjb3BlcyI6WyJjbGFzaCJdLCJsaW1pdHMiOlt7InRpZXIiOiJkZXZlbG9wZXIvc2lsdmVyIiwidHlwZSI6InRocm90dGxpbmcifSx7ImNpZHJzIjpbIjU0LjE4Ny4yMjkuNjAiLCIxNzcuMTM0LjE3OC41MCJdLCJ0eXBlIjoiY2xpZW50In1dfQ.Gc5CzDtzFmSrfrkPVX4eV4I84SpZW089Q2erjDTV-kV3CoJrydkah-e6hrGO9ExyqWnk4arKftr0JcEgxZP65A