server:
    port: 8080
    static-content: file:../clash-horn-web-client/public/
    
clash-api:
    baseUrl: https://api.clashofclans.com/v1/
    
---

spring:
    profiles: production

server:
    port: 80
    static-content: file:///app/static/