logging:
    level:
        ROOT: ERROR
        com.clashhorn: DEBUG
        org.springframework: INFO
        
server:
    port: 8080
    static-content: file:../clash-horn-web-client/public/
    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css,application/javascript,application/json
        min-response-size: 1024
    
clash-api:
    baseUrl: https://api.clashofclans.com/v1
    accessToken: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6IjNlNmMwMDQ0LWQyMDEtNGU4Yy1iNWEyLWM2NDc2ZjM5OTBjNCIsImlhdCI6MTUwNjExODcwOCwic3ViIjoiZGV2ZWxvcGVyLzNhMTk2MmY1LWNjNmYtNzg1OC0wODViLTFmN2IxMTJlNjNiNSIsInNjb3BlcyI6WyJjbGFzaCJdLCJsaW1pdHMiOlt7InRpZXIiOiJkZXZlbG9wZXIvc2lsdmVyIiwidHlwZSI6InRocm90dGxpbmcifSx7ImNpZHJzIjpbIjE3Ny45OS41My4xNjAiXSwidHlwZSI6ImNsaWVudCJ9XX0.Z51Ttdr6aVOE-THkNN3t3av5ICBXH1dkFUbMMXY4zdDLeis-VFDBRDAS3imp_G6m10LdBFdDBZ3IQnzCfOv1wg
    
---
spring:
    profiles: guilaaf-dev
    
clash-api:
    accessToken: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6IjY5YWU3ZDkxLTYzYmQtNGM2Ni1iZTYyLTgwMDIyOGU4Njc2NiIsImlhdCI6MTUwODk3NjQ2Mywic3ViIjoiZGV2ZWxvcGVyLzA5YjFlMzcyLTA2M2MtYjA1OC03YjFjLWJmNzBjNDVjNTIyYSIsInNjb3BlcyI6WyJjbGFzaCJdLCJsaW1pdHMiOlt7InRpZXIiOiJkZXZlbG9wZXIvc2lsdmVyIiwidHlwZSI6InRocm90dGxpbmcifSx7ImNpZHJzIjpbIjE5MS4yNTEuMjIzLjMxIl0sInR5cGUiOiJjbGllbnQifV19.NznlBYs5ACwe8YgXDj1mbWQC9VakKLv_3lSRLLToqUONV1dd-RtwNoJa0f-mzSyAGtdIU-WJ0vnmozT5sCfJdw

---
spring:
    profiles: production

logging:
    pattern:
        console: 
    file: /home/ec2-user/clash-horn.log

server:
    port: 80
    static-content: file:///home/ec2-user/clash-horn/clash-horn-web-client/public/
    
clash-api:
    accessToken: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6ImU1ZmJjY2IwLWE5NDktNGI2My05MTVkLWQyOTBiNzQ5ZmExNSIsImlhdCI6MTUwOTE2MDA2OCwic3ViIjoiZGV2ZWxvcGVyLzA5YjFlMzcyLTA2M2MtYjA1OC03YjFjLWJmNzBjNDVjNTIyYSIsInNjb3BlcyI6WyJjbGFzaCJdLCJsaW1pdHMiOlt7InRpZXIiOiJkZXZlbG9wZXIvc2lsdmVyIiwidHlwZSI6InRocm90dGxpbmcifSx7ImNpZHJzIjpbIjUyLjY3LjI0My4xMjIiXSwidHlwZSI6ImNsaWVudCJ9XX0.Im9FU-kH8shT5GFUdeajP8qVFtzTkelYq3B0H8JZX1ljUYfHtMuquUIbN0ba5gntkd4dLIo5Q_wwVkOXYo7lNQ
